// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cndgtyzjwjlelglieoyf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNuZGd0eXpqd2psZWxnbGllb3lmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzMDYzMzgsImV4cCI6MjA1Njg4MjMzOH0.CbHswVdSYfKw6a6mKd9sQuAcxfqA6DQdoOebqe7bzQc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);